### ISSUE TITLE
Implement audio to image data processing function. 

### ISSUE THREAD

**Issue by fentresspaul61B** [fentresspaul61B/audio_to_image_model_training#1]
I am implementing and testing the audio-to-image functions. This step is for data pre-processing in order to train an image classification model. 

## Todo 
- [x] Write unit tests for read_audio function. 
- [x] Implement read_audio function. 
- [x] Pass read_audio function test. 

- [x] Write unit tests for audio_to_melspectrogram function. 
- [x] Implement audio_to_melspectrogram function. 
- [x] Pass audio_to_melspectrogram function test. 

- [x] Write unit tests for audio_to_MFCC function. 
- [x] Implement audio_to_MFCC function. 
- [x] Pass audio_to_MFCC function test. 

- [x] Write unit tests for audio_to_chroma_stft function. 
- [x] Implement audio_to_chroma_stft function. 
- [x] Pass audio_to_chroma_stft function test. 

- [x] Clean code and write useful comments.

**Comment by fentresspaul61B** [comment]
Completed this task. I wrote tests for every audio function, and they are all passing, as well as with the automated tests using GitHub tasks, and I finished it up by cleaning up the code, writing comments, and consolidating repetitive code.
